import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, useEffect } from 'react'
import About from '../components/About'
import Contact from '../components/Contact'
import Cursor from '../components/Cursor'
import Intro from '../components/Intro'
import Nav from '../components/Nav'
import ProjectCard from '../components/ProjectCard'

const Home: NextPage = () => {
  const containerRef = useRef(null);

  return (
    <>
      <Cursor />

      <div data-scroll-container className='w-full bg-[#f0e3d6]' ref={containerRef}>
        <Head>
          <title>Joseph Jenkins -- Creative Developer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <main className='w-full px-5 sm:px-12'>
          <Intro />
          <About />
          <section className='w-full mt-24' data-scroll-section>
            <ProjectCard
              name='Shevon Salmon'
              subtext='A fan site for shevon'
              description='Redesigned the wix site that Shevon Salmon created in this project. I was able to change layout, use a monochrome style ( black and white ), added scroll animations and relatively created a redesign attractive to the eye.'
              siteLink='https://shevonsalmon.netlify.app'
              codeLink='https://github.com/JOSEPH-JENKINS/shevon-salmon-fansite.git'
            />
            <ProjectCard
              name='Axer Studios'
              subtext='A digital agency site redesign'
              description='Redesigned the Axer Studios site for fun. I was able to change layout, employ the use of good imagery, worked on alignment of elements and relatively created a redesign attractive to the eye.'
              siteLink='https://axerstudios.netlify.app'
              codeLink='https://github.com/JOSEPH-JENKINS/axer-studios.git'
            />
          </section>
          <Contact />
        </main>
      </div>
    </>
  )
}

export default Home
